### ISSUE TITLE
Update data: ca.gov domains

### ISSUE THREAD

**Issue by lukefretwell** [civichackingagency/scangov#114]
Domains: ca.gov domains from performance leaderboard

Just adding this here so we can think about how best to handle.

- [x] set up ca.scangov.org subdomain
- [x] Name: California government digital services monitor
- [x] Would be nice to figure out a way to link to subdomain on ca.gov scangov page

**Comment by lukefretwell** [comment]
@Narlotl my suggestion would be to add them to scangov.

**Comment by Narlotl** [comment]
There's 500 domains, so I don't really want to add them in with the other ones.

**Comment by Narlotl** [comment]
https://github.com/civichackingagency/scangov-ca
