### ISSUE TITLE
Add a legend to the dashboard

### ISSUE THREAD

**Issue by mgifford** [civichackingagency/scangov#128]
**Is your feature request related to a problem? Please describe.**
Looking at a page like - https://scangov.org/profile/?domain=opm.gov#overview

It would be nice to be able to have some more context about what this is. Perhaps a legend. References to where and why you have chosen these as best practices. Something to help understand what this score means.

An explainer for this with chart, symbols, and the criteria would be helpful.

**Describe the solution you'd like**
- Is this related to the 21st C Design IDEA? If so links would be good.

For instance, links to why these are important to search and government would be good:
- `<link rel="canonical">`
- `<meta property="og:image:alt">`

In general, government sites would be the canonical link, even if this wasn't stated, but it probably should be stated.

Links to references like:
- https://ahrefs.com/seo/glossary/canonical-tag
- https://swimburger.net/blog/web/dont-forget-to-provide-image-alt-meta-data-for-open-graph-and-twitter-cards-social-sharing

**Describe alternatives you've considered**
Google Lighthouse is a good example. https://developer.chrome.com/docs/lighthouse/seo/meta-description

Teams need to know why this matters.

**Comment by lukefretwell** [comment]
@mgifford we have this info on the indicator pages (below table) but plan to take a new approach (https://github.com/civichackingagency/scangov/issues/121).

These will link to specific pages in the documentation: https://docs.scangov.org/

I've incorporated your feedback: https://github.com/civichackingagency/scangov/issues/121

Closing this but re-open if I didn't address everything there.
