### ISSUE TITLE
Not all metadata is equal

### ISSUE THREAD

**Issue by mgifford** [civichackingagency/scangov#129]
**Describe the bug**
Looking at https://scangov.org/profile/?domain=opm.gov#metadata

I just want to say that not all metadata is equal, and the score can't be a 1:1 relationship of the fields.

I think the most important two values are:
- `<title>`
- `<meta name="viewport">`

Title is key for accessibility, and the viewport is key for mobile. 

I can see that `<meta name="description">` would be important for search summaries. Though not sure if these are actually used given how bad most of these tend to be.  I'm also not sure about `<link rel="canonical">` given that .gov sites don't tend to produce multiple copies. It isn't like a news site or blog. 

OpenGraph tags are important for SEO, but not as important as the Title or Viewport. 
```
<meta property="og:site_name"> 
<meta property="og:type"> 
<meta property="og:title">
<meta property="og:description">
<meta property="og:url">
<meta property="og:image">
<meta property="og:image:alt">
```

These all work as a set essentially too.  Is OpenGraph supported or not.  

**Expected behavior**
The score should reflect the impact on the user.

**Comment by lukefretwell** [comment]
@mgifford appreciate the feedback.

We know not everyone agrees with our indicators and grade/score protocol. However, we believe these are important to the government digital experience. Some of these are outside the realm of accessibility and SEO.

We do include the two values you indicate as important.
