### ISSUE TITLE
Update data: hawaii.gov

### ISSUE THREAD

**Issue by bradford-baris-ETS** [civichackingagency/scangov#138]
Domain: https://hawaii.gov

**Comment by Narlotl** [comment]
Done: https://scangov.org/profile/?domain=hawaii.gov#overview

Note for your robots score: https://hawaii.gov/robots.txt exists but it's returning a 404 status

**Comment by bradford-baris-ETS** [comment]
Team fixed it. Can I bump this to request another site scan update? If not, will re-file. Thanks!

**Comment by Narlotl** [comment]
Doing it here is fine.
I updated it and everything looks good: https://scangov.org/profile/?domain=hawaii.gov#metadata
Again, you are probably going to have to refresh twice.
