### ISSUE TITLE
Update data: healthcare.gov, cuidadodesalud.gov

### ISSUE THREAD

**Issue by bilherron** [civichackingagency/scangov#145]
Domain:  healthcare.gov
Domain: cuidadodesalud.gov

These sites have recently been updated from using `<meta name="og:*">` to `<meta property="og:*">`.

**Comment by Narlotl** [comment]
Done: https://scangov.org/profile/?domain=healthcare.gov#metadata https://scangov.org/profile/?domain=cuidadodesalud.gov#metadata
