### ISSUE TITLE
Update data: https://nv.gov

### ISSUE THREAD

**Issue by jdiarte** [civichackingagency/scangov#148]
Domain: https://nv.gov

Hi, looks like your scan did not pick up our Sitemap or Robots. If your crawler is following the robots.txt, I just need to know what to allow so you can crawl the rest of the site successfully. Not sure if you are because you were able to find the Metadata. Regardless, let me know what needs to be done so that your crawler and view both the Sitemap and robots. 

Sitemaps:
https://nv.gov/sitemap.xml
https://nv.gov/sitemap.html

Robots
https://nv.gov/robots.txt

**Comment by Narlotl** [comment]
It's picking up both of them now. Your sitemap is still responding with a content type of text/html, but otherwise everything is working.
