### ISSUE TITLE
Update data: Kansas.gov

### ISSUE THREAD

**Issue by agoodrick** [civichackingagency/scangov#162]
Domain: Kansas.gov

As suggested by Elias Fretwell in our previous update request, we have redirected "https://kansas.gov/robots.txt" to "https://portal.kansas.gov/robots.txt". Please let me know if there is any additional actions we need to take to improve our Robots and Sitemap scores. Thanks!

**Comment by Narlotl** [comment]
I thought it was working yesterday, but now https://kansas.gov/robots.txt doesn't redirect in the browser. It does redirect to https://portal.kansas.gov/ outside the browser, but not to https://portal.kansas.gov/robots.txt.

**Comment by agoodrick** [comment]
Sorry, I was just notified by our system administrator that there is an issue with the redirect he put in place. He has temporarily backed that redirect out until he can isolate the problem. I will post a new comment to this thread when the redirect is back in place.

**Comment by agoodrick** [comment]
Our SysAdmin has notified me that the redirect is back in place. I have verified that https://kansas.gov/robots.txt is now redirecting to portal.kansas.gov/robots.txt.

**Comment by Narlotl** [comment]
Done: https://scangov.org/profile/?domain=kansas.gov#robots
