### ISSUE TITLE
Update data: usccr.gov

### ISSUE THREAD

**Issue by fkildoo** [civichackingagency/scangov#163]
Domain: usccr.gov

I checked our report a few weeks ago and made changes to our metadata, but it's not picking it up on the new report from yesterday. I realized robots.txt was being overwritten every time I ran composer, so I fixed that as well. 

Can you please recheck and update our report? Thanks.

**Comment by Narlotl** [comment]
Done: https://scangov.org/profile/?domain=usccr.gov#overview
