### ISSUE TITLE
Update data: ny.gov

### ISSUE THREAD

**Issue by knaackbuilt** [civichackingagency/scangov#164]
Domain: ny.gov

Good Morning - yesterday we pushed new code to ny.gov to resolve our sitemap, robots.txt, and og:type meta, issues. Could you please re-scan ny.gov and update the dashboard? 

Thanks!
-Jeff Knaack
NY.gov Technical Director

**Comment by Narlotl** [comment]
Done: https://scangov.org/profile/?domain=ny.gov#overview
