### ISSUE TITLE
Fix share bar

### ISSUE THREAD

**Issue by lukefretwell** [civichackingagency/scangov#79]
**Is your feature request related to a problem? Please describe.**

Share is randomly placed and we should consider moving it somewhere uniformly on every page.

**Describe the solution you'd like**

Rethink navbar and add as a link there

- [ ] Fix padding
- [ ] Add aria toolbar? https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/toolbar_role

**Describe alternatives you've considered**

**Additional context**

**Comment by Narlotl** [comment]
The bar also overflows on mobile.

![Image](https://github.com/civichackingagency/gov-metadata/assets/78450405/8f646cd2-d14a-4187-821f-9b49d5bb4155)
![Image](https://github.com/civichackingagency/gov-metadata/assets/78450405/6870e164-ff33-41f4-8bdc-0a18803b4144)

**Comment by lukefretwell** [comment]
@Narlotl can you take a look at the code and clean it up?

**Comment by lukefretwell** [comment]
Fixed mobile issue.
